### ISSUE TITLE
Image does not build

### ISSUE THREAD

**Issue by oglok** [fbdlampayan/tpm-k8s-device-plugin#1]
Hi! First of all, this is a very interesting project. Thanks for sharing!

Now, I'm trying to build the Dockerfile present in the repo, but I'm getting this issue everytime:

```
Error: error building at STEP "RUN go get -v github.com/intel/intel-device-plugins-for-kubernetes/pkg/deviceplugin &&     go get -v github.com/pkg/errors &&     go get -v k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1": error while running runtime: exit status 2
```

Do you have any available image that I can directly use in the manifests? 

Thanks

**Comment by fbdlampayan** [comment]
Hi @oglok ,

I've managed to replicate the issue. It was because the golang version I had years back is too old for the recent changes in intel's library... I've now updated it to work on latest golang version.

I don't have any ready made image, but please update your copy to the recent changes I've made and you should be able to successfully build it from your end.
